version : '2'
services:
  springappserver:
    build:
      context: .
      #dockerfile: springapp.dockerfile
    working_dir: /app
    ports:
      - "8080:8080"
    networks:
      - net-spring-db
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    depends_on:
      - mysqldbserver
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker

  mysqldbserver:
    build:
      context: .
      dockerfile: mysqldb.dockerfile
    ports:
      - "3306:3306"
    networks:
      - net-spring-db
    environment:
      MYSQL_DATABASE: dockerdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    container_name: mysqldbserver

networks:
  net-spring-db:
    driver: bridge
