server:
  port: 8040

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/statusMachine?useUnicode=true&useSSL=true
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
