##数据库连接信息
spring:
  application:
    name: spring-boot-rabbitmq
  rabbitmq:
    addresses: 127.0.0.1:5672
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    publisher-returns: true
    virtual-host: /
    template:
      mandatory: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  http:
    multipart:
      max-file-size: 128KB
      max-request-size: 1280KB

server:
  address: 127.0.0.1
  port: 8088
  tomcat:
    #Tomcat是否开启压缩，默认为关闭
    compression: on
    #配置Tomcat编码，默认为UTF-8
    uri-encoding: UTF-8

