spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update  # 第一次简表create  后面用update
    show-sql: true

server:
  address: 127.0.0.1
  port: 8070
  tomcat:
    #Tomcat是否开启压缩，默认为关闭
    compression: on
    #配置Tomcat编码，默认为UTF-8
    uri-encoding: UTF-8