#springboot单据源配置

#springboot多数据源配置
#数据源1
spring:
  datasource:
    db1:
      url: jdbc:mysql://127.0.0.1:3306/db1?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
#数据源2
    db2:
      url: jdbc:mysql://127.0.0.1:3306/db2?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
#mybatis
mybatis:
  mapper-locations: "classpath*:mapper/*.xml"
  type-aliases-package: com.composite.dao

server:
  address: 127.0.0.1
  port: 8093