spring:
  data:
    mongodb:
      master:
        host: 127.0.0.1
        port: 27017
        database: db1
      slave:
        host: 127.0.0.1
        port: 27017
        database: db2
server:
  port: 8065
